name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Sync ke Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Unggah Berkas via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: 'root'
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/home/ubuntu/www/riyan.site/htdocs/'
          delete_remote_files: false
